### ISSUE TITLE
Data Ingestion: String to Float

### ISSUE THREAD

**Issue by mshearer0** [Building-ML-Pipelines/building-machine-learning-pipelines#15]
Downloaded dataset contains non-numeric zip codes ending "XX" causing conversion to fail, for example:

File "convert_data_to_tfrecords.py", line 47, in <module>
    "zip_code": _int64_feature(int(float(row["zip_code"]))),
ValueError: could not convert string to float: '113XX'

Replacing XX with 00 allows conversion to proceed.

**Comment by hanneshapke** [comment]
Hi @mshearer0,

I have updated the ingestion example with a conversion function.
https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/commit/2f2c8e91bde2d22b0a0c6f6eb71e65a2a8732449

I hope the solutions works on your side.

Thank you for letting us know about the issue.
- Hannes

**Comment by mshearer0** [comment]
Thanks - that was my solution too
