### ISSUE TITLE
Data Validation: 26k file

### ISSUE THREAD

**Issue by mshearer0** [Building-ML-Pipelines/building-machine-learning-pipelines#16]
How do i create the file '26k-consumer-complaints-modified.csv' for data validation script?

**Comment by hanneshapke** [comment]
Hi @mshearer0, 

I have extended the example notebook with the file split. The updated version can be found here: https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/blob/master/chapters/data_validation/data_validation.ipynb

Let me know if you have further questions, 
Hannes

**Comment by mshearer0** [comment]
Thanks - did you just change the source file?

The file is html not a json-formatted notebook

**Comment by hanneshapke** [comment]
Oh wow. I edited the file with VS Code. Didn't see different behavior on my end. Let me see if I can re-upload the file.

**Comment by hanneshapke** [comment]
@mshearer0 Any chance Github has problems rendering the notebooks at the moment?
All notebooks in the repo are presented as HTML -> https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/blob/master/chapters/data_privacy/differential_privacy.ipynb (which I haven't touched today)

**Comment by mshearer0** [comment]
Yes, that file is also displaying as HTML
