### ISSUE TITLE
Image not publicly visible in gcr.io container registry

### ISSUE THREAD

**Issue by mshearer0** [Building-ML-Pipelines/building-machine-learning-pipelines#29]
Error pulling image /oreilly-book/ml-pipelines-tfx-custom:0.22.0 from container registry gcr.io. Is it globally visible?

**Comment by mshearer0** [comment]
Building a deploying my own custom image with tensorflow-hub following instructions on pg 317,318 allows kubeflow pipeline to complete

Updating pipeline_kubeflow_gcp_buckets.py:

input_bucket and output_bucket to point to my cloud storage bucket (and copying over data and components folders to that location).

tfx_image = os.environ.get(
        "KUBEFLOW_TFX_IMAGE",
        "gcr.io/<insert your project_id>/ml-pipelines-tfx-custom:0.22.0",

**Comment by hanneshapke** [comment]
Thank you @mshearer0 You raise a good point. I'll make the gcr url dynamic.

**Comment by hanneshapke** [comment]
@mshearer0 If you have a moment, please check out https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/pull/31 and let me know if the implementation would work for you.

**Comment by mshearer0** [comment]
Thanks, should pipeline.py also be updated

And

tfx_image = os.environ.get(
        "KUBEFLOW_TFX_IMAGE",
        "gcr.io/oreilly-book/ml-pipelines-tfx-custom:0.21.4",
    )

In pipeline_gcp_cloud_ai.py?

**Comment by jazzsir** [comment]
@hanneshapke  #31 does not work for me, could you tell me a proper image path?

**Comment by mshearer0** [comment]
@jazzsir - did you build and deploy your own image into gcr.io?

**Comment by jazzsir** [comment]
@mshearer0 I finally applied my custom image to my own registry server, thanks

**Comment by jazzsir** [comment]
@hanneshapke did you run [kubeflow example code](https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/blob/master/pipelines/kubeflow_pipelines/pipeline_kubeflow.py) without any errors at all? my case #36

**Comment by hanneshapke** [comment]
Hi @jazzsir,

Yes, it did. Could it be a permission issue to the Google Container Registry or GCS?

- Hannes

PS: Check out the latest updates to the example code: https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/releases/tag/examples_based_on_tfx_1.4
