### ISSUE TITLE
Differential Privacy - Fix for differentially private optimizer not called

### ISSUE THREAD

**Issue by mshearer0** [Building-ML-Pipelines/building-machine-learning-pipelines#32]
model.fit produces:

AssertionError: compute_gradients() on the differentially private optimizer was not called. Which means that the training is not differentially private. It happens for example in Keras training in TensorFlow 2.0+.

Using modified optimiser [here](https://github.com/tensorflow/privacy/issues/106#issuecomment-632730284) allowed fit to complete.

**Comment by hanneshapke** [comment]
Hi @mshearer0,

I have made some tweaks to the example a few days ago. It requires `tf-nightly`. Feel free to check out the example branch: https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/tree/updated-privacy-example

- Hannes

**Comment by mshearer0** [comment]
Hi Hannes, yes I spotted that and used the new version from the pull request branch but got the same error. Using the modified optimiser works ok
