### ISSUE TITLE
Makefile `install-deps` fails

### ISSUE THREAD

**Issue by austinkeller** [Building-ML-Pipelines/building-machine-learning-pipelines#38]
https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/blob/35a545a4f39d58d2f58e9d7988acb2f5146ca460/Makefile#L23

This should be changed to `requirements/test_requirements.txt`

**Comment by hanneshapke** [comment]
Hi @austinkeller, 

Thank you for reporting this issue. A fix was committed here (https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/commit/98bff804dcd1ee14e9567167893888b751b90c61) and is now available on the `main` branch.

- Hannes
