### ISSUE TITLE
The way to extend BaseExampleGenExecutor has changed in version 0.23

### ISSUE THREAD

**Issue by asimonw** [Building-ML-Pipelines/building-machine-learning-pipelines#43]
In your example code for writing a custom component by extending BaseExampleGenExecutor (see [Custom_TFX_Components](https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/blob/master/chapters/adv_tfx/Custom_TFX_Components.ipynb) notebook), your `ImageToExample ` function should no longer accept an `input_dict` explicitly.

This has changed since version 0.23. The input base can now simply be found at `exec_properties['input_base']`. The code as is will result in an error in more recent versions. Hope this helps keeping this valuable resource (thanks for that, btw!) up to date.

**Comment by hanneshapke** [comment]
Hi @asimonw,

Thank you for filing this issue! I have updated the example (https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/commit/3c446b4863d5b2f2a5109bc617eaedec0ec5922d) and upgraded the repo to TFX 1.4.

Thank you again for raising this issue!
