### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by eliwilner** [Building-ML-Pipelines/building-machine-learning-pipelines#44]
I'm trying to execute the basic_pipeline.py with the example code on chapter 2.

However, I get the following error:
`WARNING:apache_beam.internal.gcp.auth:Unable to find default credentials to use: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Connecting anonymously.`

Can anyone help me to set up the credentials correctly?

Thank you

**Comment by hanneshapke** [comment]
Hi @eliwilner , 

Do you mean `base_pipeline.py`? That pipeline isn't designed to be executed on its own. It is rather consumed by the pipelines in the subdirectories.

Also, what type of pipeline are you trying to run? Local, or GCP?

Let me know if I misunderstood your error here.
