### ISSUE TITLE
Modification for `pre-experiment-pipeline/experiment_6Mar.ipynb`

### ISSUE THREAD

**Issue by Anylee2142** [Building-ML-Pipelines/building-machine-learning-pipelines#50]
## Problem
In [pre-experiment-pipeline/experiment_6Mar.ipynb](https://github.com/Anylee2142/building-machine-learning-pipelines/blob/modify_notebook_example/pre-experiment-pipeline/experiment_6Mar.ipynb)
1. Incorrect file path for dataframe
2. Incompatible pandas arguments passed to `df['zip_code'].str.replace(...)`

## System details
OS name and version: Ubuntu 18.04
Package versions: tensorflow 2.2.0 | tfx 0.22.0
Local setup: virtualenv + `make develop`

## Fix
1. Replace original file path `../data/6Mar/consumer_complaints_with_narrative.csv` to `../data/consumer_complaints_with_narrative.csv` in shell 6
2. Remove `regex=True` from df['zip_code'] = df['zip_code'].str.replace('X', '0') in shell 11 and 12, to be consistent with pandas=0.22.0

Also, in order to pass `make test` I modified the name of `/requirements/test_requirements.txt`, which #38 addressed.

**Comment by hanneshapke** [comment]
Hi @Anylee2142,

The import path was fixed here: https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/commit/269b033461baca1bb996ec36733d81fc368d0755
The problem around the incompatible pandas arguments seems to be resolved with the updated Python dependencies.

Thank you for reporting the issue! Please reopen this issue if the problem persists.

Hannes
