### ISSUE TITLE
Dockerfile for creating image used to Train

### ISSUE THREAD

**Issue by jashshah** [Building-ML-Pipelines/building-machine-learning-pipelines#54]
Hello, can we get the `Dockerfile` used for creating the image `gcr.io/oreilly-book/ml-pipelines-tfx-custom:0.22.0`?

**Comment by hanneshapke** [comment]
Hi @jashshah, the `Dockerfile` is part of the repo: https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/blob/main/pipelines/kubeflow_pipelines/tfx-docker-image/Dockerfile

An update is following in a few hours.

**Comment by hanneshapke** [comment]
Hi @jashshah,

Check out the latest updates to the example code: https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/releases/tag/examples_based_on_tfx_1.4

- Hannes
